name: weyyak-preprod-xms
on:
  workflow_dispatch: # Enable manual triggering
    inputs:
      service : 
        description : 'Name of the Service'
        required : true
        default: 'User'
        type: choice
        options:
        - User
        - Module
        - Frontend
        - Frontend-Config
      tag_id:
        description: 'Tag ID'
        required: true
      branch_name:
        description: 'Branch Name'
        required: true
    
jobs:
  configure:
    name: Configure the Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set variable based on condition
        id: set-variable
        run: |
          if [ "${{ inputs.service }}" == "Module" ]; then
            echo "SERVICE_PATH=xms/core/api/module-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-preprod-xms-module" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-preprod-xms-module" >> $GITHUB_OUTPUT
            echo "YAML=module.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Frontend" ]; then
            echo "SERVICE_PATH=xms/core/api/frontend-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-preprod-xms-frontend" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-preprod-xms-frontend" >> $GITHUB_OUTPUT
            echo "YAML=frontend.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Frontend-Config" ]; then
            echo "SERVICE_PATH=xms/customer/weyyak/frontend-config-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-preprod-xms-frontend-config" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-preprod-xms-frontend-config" >> $GITHUB_OUTPUT
            echo "YAML=frontend-config.yaml" >> $GITHUB_OUTPUT
          else
            echo "SERVICE_PATH=xms/core/api/user-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-preprod-xms-user" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-preprod-xms-user" >> $GITHUB_OUTPUT
            echo "YAML=user.yaml" >> $GITHUB_OUTPUT
          fi
  display-values:
    name: Display Values of the Variables
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Display all Values
        run: |
          echo "SERVICE_PATH is ${{ needs.configure.outputs.SERVICE_PATH }}"
          echo "REPOSITORY is ${{ needs.configure.outputs.REPOSITORY }}"
          echo "IMAGE is ${{ needs.configure.outputs.IMAGE }}"
          echo "YAML is ${{ needs.configure.outputs.YAML }}"
