on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - macos-13
        - windows-latest
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      # - name: My first step - check out repository
      #   uses: actions/checkout@v4
      - name: My Second Step
        run: |
             echo this is running on ${{ inputs.chosen-os}}
             echo "::debug::Set the dubug variable"
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo  "this is called Group"
            echo "::endgroup::"
  
