on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - macOS
        - windows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello world .
