name: weyyak-qa-xms
run-name: ${{ inputs.service }} - ${{inputs.tag_id}}
on:
  workflow_dispatch: # Enable manual triggering
    inputs:
      service : 
        description : 'Name of the Service'
        required : true
        default: 'User'
        type: choice
        options:
        - User
        - Module
        - Wrapper
        - Frontend-Config
      tag_id:
        description: 'Tag ID'
        required: true
      branch_name:
        description: 'Branch Name'
        required: true
env:
  PROJECT_ID: testing-400312
  GKE_LOCATION: asia-south1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: engro-wykqa # TODO: update to cluster name
  NAMESPACE: weyyak-xms
jobs:
  configure:
    name: Configure the Deployment
    runs-on: ubuntu-latest
    outputs:
      SERVICE_PATH: ${{ steps.set-variable.outputs.SERVICE_PATH }}
      REPOSITORY: ${{ steps.set-variable.outputs.REPOSITORY }}
      IMAGE: ${{ steps.set-variable.outputs.IMAGE }}
      YAML: ${{ steps.set-variable.outputs.YAML }}
    steps:
      - name: Set variable based on condition
        id: set-variable
        run: |
          if [ "${{ inputs.service }}" == "Module" ]; then
            echo "SERVICE_PATH=xms/core/api/module-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-module" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-module" >> $GITHUB_OUTPUT
            echo "YAML=module.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Wrapper" ]; then
            echo "SERVICE_PATH=xms/customer/weyyak/wrapper-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-xms-wraper-api-qa" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-xms-wraper-api-qa" >> $GITHUB_OUTPUT
            echo "YAML=wraper-api.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Frontend-Config" ]; then
            echo "SERVICE_PATH=xms/customer/weyyak/frontend-config-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-frontend-config" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-frontend-config" >> $GITHUB_OUTPUT
            echo "YAML=frontendconfig.yaml" >> $GITHUB_OUTPUT
          else
            echo "SERVICE_PATH=xms/core/api/user-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-user" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-user" >> $GITHUB_OUTPUT
            echo "YAML=user.yaml" >> $GITHUB_OUTPUT
          fi
  display-values:
    name: Display Values of the Variables
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Display all Values
        run: |
          echo "SERVICE_PATH is ${{ needs.configure.outputs.SERVICE_PATH }}"
          echo "REPOSITORY is ${{ needs.configure.outputs.REPOSITORY }}"
          echo "IMAGE is ${{ needs.configure.outputs.IMAGE }}"
          echo "YAML is ${{ needs.configure.outputs.YAML }}"
          echo "PROJECT_ID is ${{env.PROJECT_ID}} "
          echo "GKE_LOCATION is ${{env.GKE_LOCATION}} "
          echo "GKE_CLUSTER is ${{env.GKE_CLUSTER}} "
          echo "NAMESPACE is ${{env.NAMESPACE}} "
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    needs: configure
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: cloning dev repository
      run: |-
        git clone git@github.com:engrotech/xms.git -b "${{ inputs.branch_name }}"
        cd ${{ needs.configure.outputs.SERVICE_PATH }}
    
    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH_QA_WYK_XMS }}'

    - name: Docker configuration
      run: |-
        gcloud auth configure-docker ${{ env.GKE_LOCATION }}-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_LOCATION }}

    # Build and Publish the Docker image
    - name: Build and Publish
      run: |-
        cd ${{ needs.configure.outputs.SERVICE_PATH }}
        docker build -t $IMAGE . --build-arg CONFIG_FILE=weyyak-qa.json
        docker tag $IMAGE:latest $GKE_LOCATION-docker.pkg.dev/$PROJECT_ID/${{ needs.configure.outputs.REPOSITORY }}/${{ needs.configure.outputs.IMAGE }}:"${{ inputs.tag_id }}"
        docker push $GKE_LOCATION-docker.pkg.dev/$PROJECT_ID/${{ needs.configure.outputs.REPOSITORY }}/${{ needs.configure.outputs.IMAGE }}:"${{ inputs.tag_id }}"
           
    - name: Deploy
      run: |-
        git clone git@github.com:engrotech/pipelines-weyyak-kubernetes.git -b "weyyak-qa-xms"
        cd pipelines-weyyak-kubernetes/deployments
        pwd
        sed -i "s/$IMAGE:.*/$IMAGE:${{ inputs.tag_id }}/g" ${{ needs.configure.outputs.YAML }}
        kubectl apply -f ${{ needs.configure.outputs.YAML }}
