on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - macos-13
        - windows-latest
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
       - name: Set the value
         id: step_one
         run: |
           echo "action_state=yellow1" >> "$GITHUB_ENV"
       - name: Use the value
         id: step_two
         run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

          

  
