on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - macos-13
        - windows-latest

jobs:
  test:
    runs-on: ${{ inputs.chosen-os}}
    steps:
    - run: echo Hello ${{ inputs.chosen-os}} .
