name: weyyak-qa-xms-test
run-name: ${{ inputs.service }} is learning GitHub Actions
on:
  workflow_dispatch: # Enable manual triggering
    inputs:
      service : 
        description : 'Name of the Service'
        required : true
        default: 'User'
        type: choice
        options:
        - User
        - Module
        - Wrapper
        - Frontend-Config
      tag_id:
        description: 'Tag ID'
        required: true
      branch_name:
        description: 'Branch Name'
        required: true
env:
  PROJECT_ID: testing-400312
  GKE_LOCATION: asia-south1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: engro-wykqa # TODO: update to cluster name
  NAMESPACE: weyyak-xms
jobs:
  configure:
    name: Configure the Deployment
    runs-on: ubuntu-latest
    outputs:
      SERVICE_PATH: ${{ steps.set-variable.outputs.SERVICE_PATH }}
      REPOSITORY: ${{ steps.set-variable.outputs.REPOSITORY }}
      IMAGE: ${{ steps.set-variable.outputs.IMAGE }}
      YAML: ${{ steps.set-variable.outputs.YAML }}
    steps:
      - name: Set variable based on condition
        id: set-variable
        run: |
          if [ "${{ inputs.service }}" == "Module" ]; then
            echo "SERVICE_PATH=xms/core/api/module-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-module" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-module" >> $GITHUB_OUTPUT
            echo "YAML=module.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Wrapper" ]; then
            echo "SERVICE_PATH=xms/customer/weyyak/wrapper-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wyk-xms-wraper-api-qa" >> $GITHUB_OUTPUT
            echo "IMAGE=wyk-xms-wraper-api-qa" >> $GITHUB_OUTPUT
            echo "YAML=wraper-api.yaml" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.service }}" == "Frontend-Config" ]; then
            echo "SERVICE_PATH=xms/customer/weyyak/frontend-config-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-frontend-config" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-frontend-config" >> $GITHUB_OUTPUT
            echo "YAML=frontendconfig.yaml" >> $GITHUB_OUTPUT
          else
            echo "SERVICE_PATH=xms/core/api/user-api" >> $GITHUB_OUTPUT
            echo "REPOSITORY=wykqa-user" >> $GITHUB_OUTPUT
            echo "IMAGE=wykqa-user" >> $GITHUB_OUTPUT
            echo "YAML=user.yaml" >> $GITHUB_OUTPUT
          fi
  display-values:
    name: Display Values of the Variables
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Display all Values
        run: |
          echo "SERVICE_PATH is ${{ needs.configure.outputs.SERVICE_PATH }}"
          echo "REPOSITORY is ${{ needs.configure.outputs.REPOSITORY }}"
          echo "IMAGE is ${{ needs.configure.outputs.IMAGE }}"
          echo "YAML is ${{ needs.configure.outputs.YAML }}"
          echo "PROJECT_ID is ${{env.PROJECT_ID}} "
          echo "GKE_LOCATION is ${{env.GKE_LOCATION}} "
          echo "GKE_CLUSTER is ${{env.GKE_CLUSTER}} "
          echo "NAMESPACE is ${{env.NAMESPACE}} "
